services:
  discord-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-mcp-server
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - MCP_BEARER_TOKEN=${MCP_BEARER_TOKEN}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8085/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
